In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl

In [2]:
result=pd.read_excel('/Users/xie/Downloads/Qishon/订单路由问题/result_10000.xlsx')
store=pd.read_excel('/Users/xie/Downloads/Qishon/订单路由问题/数据/仓库档案.xlsx')
order=pd.read_excel('/Users/xie/Downloads/Qishon/订单路由问题/数据/零售小票.xlsx')
stock=pd.read_excel('/Users/xie/Downloads/Qishon/订单路由问题/数据/库存数据.xlsx')

In [3]:
def dropsomestr(x):
    x=x.replace('\n','')
    x=x.replace('.',',')
    x=x.replace('[','')
    x=x.replace(']','')
    x=x.replace(',','')
    x=x.replace(' ','')
    x=np.array([int(i) for i in list(x)])
    x=np.reshape(x,(-1,30))
    return(x)
result['发货情况']=result['发货情况'].apply(dropsomestr)
result['size']=[x.size for x in result['发货情况']]

In [4]:
result.reset_index(inplace=True)
result

,index,min_cost,商品代码,发货情况,size
0,xp20180808969766,2.000000,['115590204821'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,...",30
1,xp20180808660875,4.885706,['115590104520'],"[[0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
2,xp20180808195676,3.000000,['115590104513'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
3,xp20180808672247,9.048107,['111550101206'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
4,xp20180808530971,6.298378,['111570702915'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
5,xp20180808538189,3.000000,['111570702915'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
6,xp20180808198977,7.252576,['111560101217'],"[[0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
7,xp20180808353668,7.909796,['111570202654'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
8,xp20180808750234,34.536610,['111560502673'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,...",30
9,xp20180808323238,3.000000,['111570701913'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
10,xp20180808428617,4.000000,['111F60601637'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
11,xp20180808791920,6.818102,['111F60201676'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
12,xp20180808115061,3.000000,['111560201933'],"[[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0,...",30
13,xp20180808443389,4.885706,['111F60601631'],"[[0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
14,xp20180808868429,5.000000,['111550501704'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,...",30
15,xp20180808247641,4.000000,['111550501709'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
16,xp20180808766837,6.071482,['111560402905'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
17,xp20180808702934,4.000000,['91400130-000'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
18,xp20180808208015,4.000000,['115590109513'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
19,xp20180808276369,5.000000,['111550101253'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
20,xp20180808872929,7.405784,['111570701918'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0,...",30
21,xp20180808859600,5.000000,['111F60201673'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
22,xp20180808351374,10.120368,['111560702242'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
23,xp20180808457061,5.000000,['115590104009'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
24,xp20180808223843,5.000000,['115590104524'],"[[0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0,...",30
25,xp20180808879562,3.000000,['111550402604'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
26,xp20180808731074,6.071482,['111560301904'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
27,xp20180808235832,6.298378,['111550403869'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
28,xp20180808964155,3.000000,['111560301904'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
29,xp20180808931225,3.000000,['111550302600'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
...,...,...,...,...,...
9917,xp20180808885258,4.000000,['111640404705'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9918,xp20180808348409,6.298378,['111630401002'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9919,xp20180808703669,3.000000,['111640404221'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9920,xp20180808447592,4.885706,['115590105565'],"[[0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9921,xp20180808273611,8.105331,['191630802069'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9922,xp20180808284734,7.252576,"['111640602184', '111630602623']","[[0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",60
9923,xp20180808125779,7.000000,"['171630402461', '111640602162']","[[0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0,...",60
9924,xp20180808630266,6.071482,['171640602803'],"[[0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0,...",30
9925,xp20180808503342,4.000000,['111630504010'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9926,xp20180808888467,12.244419,['191620802047'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,...",30
9927,xp20180808913691,3.000000,['171630602667'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9928,xp20180808336485,5.548709,['111630602009'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9929,xp20180808615510,2.000000,['111640602254'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0,...",30
9930,xp20180808639422,11.578951,['111640602250'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9931,xp20180808897840,15.469487,['171640602763'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9932,xp20180808836137,4.000000,['171640602712'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9933,xp20180808319494,3.000000,['111630602225'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9934,xp20180808238325,15.469487,['171630602611'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9935,xp20180808506469,5.000000,['111640602288'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0,...",30
9936,xp20180808148536,6.000000,['1A1530501001'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0,...",30
9937,xp20180808918690,6.954471,['111620402210'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9938,xp20180808811866,5.000000,['111610402680'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,...",30
9939,xp20180808257717,5.713006,['111640402723'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9940,xp20180808505612,3.000000,['171630602667'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9941,xp20180808146355,5.000000,['171640504801'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,...",30
9942,xp20180808871912,10.111321,['171630602663'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9943,xp20180808134623,3.000000,['171630602600'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9944,xp20180808988935,2.000000,['111640602004'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9945,xp20180808316531,7.649186,['111630602221'],"[[0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30
9946,xp20180808391374,4.000000,['171640602767'],"[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...",30

In [5]:
order[order['单据编号']=='xp20180808620479']

,单据编号,商品代码,商品名称,颜色代码,尺码代码,数量,收货地址
75,xp20180808620479,111F50402923,无褶休闲裤,1,606,4,吉林省延边朝鲜族自治州珲春市
10084,xp20180808620479,171640602768,蓝标男装圆领短袖T恤,4,107,2,吉林省延边朝鲜族自治州珲春市

In [12]:
order_for_test=locals()
s=0
for i in result[(result['size']>60)]['index']:
    s=s+1
    print(s,i)
    order_for_test[i]=pd.DataFrame(store)
    index_num=result[(result['index']==i)].index.tolist()
    order_for_test[i+'_result']=pd.DataFrame(result['发货情况'][index_num[0]]).T
    order_for_test[i]=pd.concat([order_for_test[i+'_result'],order_for_test[i]],axis=1)
    address=order[(order['单据编号']==i)]['收货地址'].reset_index()
    order_for_test[i]['收货地址']=address['收货地址'][0]
    order_num=order[(order['单据编号']==i)]['数量']
    for j in order[(order['单据编号']==i)]['商品代码']:
        count=order[(order['单据编号']==i)&(order['商品代码']==j)].index.tolist()
        count=count[0]
        order_num_new=order_num[count]
        order_for_test[i]['下单数'+'{}'.format(j)]=order_num_new
        order_for_test[i]['库存数'+'{}'.format(j)]=0
        for k in order_for_test[i].index:
            a=order_for_test[i]['仓库名称'][k]
            b=stock[(stock['商品代码']==j) & (stock['仓库名称']==a)]
            order_for_test[i]['库存数'+'{}'.format(j)][k]=b['数量'].sum()
    order_for_test[i].to_csv('/Users/xie/Downloads/Qishon/订单路由问题/数据/result'+'{}'.format(i)+'.csv')

1 xp20180808671789

/Users/xie/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

2 xp20180808470545
3 xp20180808205916
4 xp20180808897981
5 xp20180808968295
6 xp20180808961834
7 xp20180808672658
8 xp20180808317946
9 xp20180808416788
10 xp20180808763599
11 xp20180808504784
12 xp20180808298718
13 xp20180808561141
14 xp20180808213974
15 xp20180808524455
16 xp20180808885055
17 xp20180808370506
18 xp20180808943578
19 xp20180808768557
20 xp20180808503877

In [16]:
xp20180808213974

,0,1,2,仓库代码,仓库名称,仓库地址,仓库优先级,收货地址,下单数115590204819,库存数115590204819,下单数115650104044,库存数115650104044,下单数111650601587,库存数111650601587
0,0,0,0,CK001,北京仓,北京市北京,2,西藏自治区拉萨市墨竹工卡县,4,255,4,0,2,98
1,0,0,0,CK002,上海仓,上海市上海,3,西藏自治区拉萨市墨竹工卡县,4,73,4,83,2,36
2,0,0,0,CK003,天津仓,天津市天津,1,西藏自治区拉萨市墨竹工卡县,4,65,4,86,2,77
3,0,0,0,CK004,重庆仓,重庆市重庆,5,西藏自治区拉萨市墨竹工卡县,4,198,4,248,2,118
4,0,0,0,CK005,黑龙仓,黑龙江省哈尔滨,4,西藏自治区拉萨市墨竹工卡县,4,91,4,44,2,203
5,0,0,0,CK006,吉林仓,吉林省长春,3,西藏自治区拉萨市墨竹工卡县,4,210,4,0,2,118
6,0,0,0,CK007,辽宁仓,辽宁省沈阳,4,西藏自治区拉萨市墨竹工卡县,4,232,4,0,2,263
7,0,0,0,CK008,内蒙仓,内蒙古呼和浩特,2,西藏自治区拉萨市墨竹工卡县,4,44,4,95,2,220
8,0,0,0,CK009,河北仓,河北省石家庄,6,西藏自治区拉萨市墨竹工卡县,4,41,4,180,2,0
9,0,0,0,CK010,新疆仓,新疆乌鲁木齐,5,西藏自治区拉萨市墨竹工卡县,4,304,4,178,2,164
10,0,0,0,CK011,甘肃仓,甘肃省兰州,1,西藏自治区拉萨市墨竹工卡县,4,539,4,117,2,280
11,0,0,0,CK012,青海仓,青海省西宁,5,西藏自治区拉萨市墨竹工卡县,4,268,4,239,2,196
12,0,0,0,CK013,陕西仓,陕西省 西安,4,西藏自治区拉萨市墨竹工卡县,4,79,4,0,2,472
13,0,0,0,CK014,宁夏仓,宁夏银川,7,西藏自治区拉萨市墨竹工卡县,4,68,4,270,2,21
14,0,0,0,CK015,河南仓,河南省郑州,6,西藏自治区拉萨市墨竹工卡县,4,150,4,267,2,173
15,0,0,0,CK016,山东仓,山东省济南,3,西藏自治区拉萨市墨竹工卡县,4,81,4,203,2,366
16,0,0,0,CK017,山西仓,山西省太原,2,西藏自治区拉萨市墨竹工卡县,4,134,4,177,2,88
17,0,0,0,CK018,安徽仓,安徽省合肥,3,西藏自治区拉萨市墨竹工卡县,4,166,4,40,2,143
18,0,0,0,CK019,湖北仓,湖北省武汉,2,西藏自治区拉萨市墨竹工卡县,4,138,4,360,2,117
19,0,0,0,CK020,湖南仓,湖南省长沙,4,西藏自治区拉萨市墨竹工卡县,4,212,4,99,2,93
20,0,0,0,CK021,江苏仓,江苏 苏 南京,3,西藏自治区拉萨市墨竹工卡县,4,43,4,49,2,41
21,0,0,0,CK022,四川仓,四川省成都,2,西藏自治区拉萨市墨竹工卡县,4,338,4,0,2,40
22,0,0,0,CK023,贵州仓,贵州省贵阳,3,西藏自治区拉萨市墨竹工卡县,4,397,4,42,2,86
23,0,2,2,CK024,云南仓,云南省昆明,2,西藏自治区拉萨市墨竹工卡县,4,77,4,307,2,74
24,0,0,0,CK025,广西仓,广西省南宁,4,西藏自治区拉萨市墨竹工卡县,4,112,4,0,2,126
25,4,2,0,CK026,西藏仓,西藏拉萨,2,西藏自治区拉萨市墨竹工卡县,4,61,4,68,2,3
26,0,0,0,CK027,浙江仓,浙江省杭州,3,西藏自治区拉萨市墨竹工卡县,4,187,4,20,2,0
27,0,0,0,CK028,江西仓,江西省南昌,3,西藏自治区拉萨市墨竹工卡县,4,31,4,112,2,69
28,0,0,0,CK029,广东仓,广东省广州,2,西藏自治区拉萨市墨竹工卡县,4,281,4,138,2,205
29,0,0,0,CK030,福建仓,福建省福州,1,西藏自治区拉萨市墨竹工卡县,4,0,4,202,2,192

In [16]:
pd.read_csv('/Users/xie/Downloads/Qishon/订单路由问题/数据/resultxp20180808579487.csv')

,Unnamed: 0,0,仓库代码,仓库名称,仓库地址,仓库优先级,收货地址,下单数111F50402924,库存数111F50402924
0,0,0,CK001,北京仓,北京市北京,2,甘肃省白银市景泰县,4,285
1,1,0,CK002,上海仓,上海市上海,3,甘肃省白银市景泰县,4,272
2,2,0,CK003,天津仓,天津市天津,1,甘肃省白银市景泰县,4,444
3,3,0,CK004,重庆仓,重庆市重庆,5,甘肃省白银市景泰县,4,197
4,4,0,CK005,黑龙仓,黑龙江省哈尔滨,4,甘肃省白银市景泰县,4,298
5,5,0,CK006,吉林仓,吉林省长春,3,甘肃省白银市景泰县,4,145
6,6,0,CK007,辽宁仓,辽宁省沈阳,4,甘肃省白银市景泰县,4,106
7,7,0,CK008,内蒙仓,内蒙古呼和浩特,2,甘肃省白银市景泰县,4,126
8,8,0,CK009,河北仓,河北省石家庄,6,甘肃省白银市景泰县,4,131
9,9,0,CK010,新疆仓,新疆乌鲁木齐,5,甘肃省白银市景泰县,4,202
10,10,4,CK011,甘肃仓,甘肃省兰州,1,甘肃省白银市景泰县,4,67
11,11,0,CK012,青海仓,青海省西宁,5,甘肃省白银市景泰县,4,394
12,12,0,CK013,陕西仓,陕西省 西安,4,甘肃省白银市景泰县,4,185
13,13,0,CK014,宁夏仓,宁夏银川,7,甘肃省白银市景泰县,4,0
14,14,0,CK015,河南仓,河南省郑州,6,甘肃省白银市景泰县,4,116
15,15,0,CK016,山东仓,山东省济南,3,甘肃省白银市景泰县,4,227
16,16,0,CK017,山西仓,山西省太原,2,甘肃省白银市景泰县,4,261
17,17,0,CK018,安徽仓,安徽省合肥,3,甘肃省白银市景泰县,4,323
18,18,0,CK019,湖北仓,湖北省武汉,2,甘肃省白银市景泰县,4,14
19,19,0,CK020,湖南仓,湖南省长沙,4,甘肃省白银市景泰县,4,51
20,20,0,CK021,江苏仓,江苏 苏 南京,3,甘肃省白银市景泰县,4,317
21,21,0,CK022,四川仓,四川省成都,2,甘肃省白银市景泰县,4,268
22,22,0,CK023,贵州仓,贵州省贵阳,3,甘肃省白银市景泰县,4,81
23,23,0,CK024,云南仓,云南省昆明,2,甘肃省白银市景泰县,4,210
24,24,0,CK025,广西仓,广西省南宁,4,甘肃省白银市景泰县,4,104
25,25,0,CK026,西藏仓,西藏拉萨,2,甘肃省白银市景泰县,4,111
26,26,0,CK027,浙江仓,浙江省杭州,3,甘肃省白银市景泰县,4,150
27,27,0,CK028,江西仓,江西省南昌,3,甘肃省白银市景泰县,4,95
28,28,0,CK029,广东仓,广东省广州,2,甘肃省白银市景泰县,4,209
29,29,0,CK030,福建仓,福建省福州,1,甘肃省白银市景泰县,4,24